Make googletest 1.17.0 compatible with new Bazel 9.1.1.
Without this, I have this error:

```
ERROR: Traceback (most recent call last):
	File "/some_local_path/external/googletest+/BUILD.bazel", line 79, column 11, in <toplevel>
		cc_library(
	File "/virtual_builtins_bzl/bazel/exports.bzl", line 40, column 9, in _removed_rule_failure
Error in fail: 
         This rule has been removed from Bazel. Please add a `load()` statement for it.
         This can also be done automatically by running:
         buildifier --lint=fix <path-to-BUILD-or-bzl-file>
```