Fix boost.beast@1.88.0.bcr.1 (#5699)
WARNING: This PR modifies an already published module

By accident, I copied the wrong `MODULE.bazel` and `BUILD.bazel` file
(did take the ones from `1.87.0` and not `1.87.0.bcr.1`).

This PR fixes this. I propose to modify the existing
`boost.beast@1.88.0.bcr.1`

In the current version, you get compiler errors such as:

```
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::http::basic_parser<false>::put(boost::asio::const_buffer, boost::system::error_code&)'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::http::to_string(boost::beast::http::verb)'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::iless::operator()(boost::core::basic_string_view<char>, boost::core::basic_string_view<char>) const'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::http::basic_parser<false>::put_eof(boost::system::error_code&)'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::http::detail::trim(boost::core::basic_string_view<char>)'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::iequals(boost::core::basic_string_view<char>, boost::core::basic_string_view<char>)'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::http::to_string(boost::beast::http::field)'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::http::make_error_code(boost::beast::http::error)'
bazel-out/k8-fastbuild/bin/_solib_k8/libokapi_Scli_Slibbenchmark.so: error: undefined reference to 'boost::beast::http::token_list::const_iterator::increment()'
```

Therefore, this will cause less harm than it will be useful.