Fix two issues with the Bazel build file for libpfm
1) The file `pfmlib_torrent.c` is PowerPC-specific. Its presence in the
   generic source file list leads to build failures on other platforms,
   so remove it. It is already present in the PowerPC-specific source
   list in `POWERPC_SRCS_COMMON` so there is no need to modify it.

2) Stop setting `strip_include_prefix`, which is redundant with the
   existing `includes = [ "include" ]`. `strip_include_prefix` causes
   Bazel to specify the header path to the compiler using a `-I` flag. If
   the consuming project builds with a flag such as `-pedantic-errors`,
   it will encounter build errors such as the one below. Because paths
   specified via `includes` are translated into `-isystem` flags, which
   suppress warnings in headers, this issue is avoided.

```
bazel-out/aarch64-fastbuild/bin/external/libpfm+/_virtual_includes/pfm/perfmon/pfmlib.h:657:16: error: ISO C++ prohibits anonymous structs [-Wpedantic]
  657 |         struct {
      |                ^
```