Enable angled sqlite3 include (#3818)
Enable angled sqlite3 `#include` (by adding `includes = ["."]`) since
this is what most third-party code uses.

I injected a simple smoke test that runs in presubmit bazelci. 

Before (without `includes = ["."]`):
```console
❯ bzt @sqlite3//... --test_output=all
(...)
ERROR: /home/laltenmueller/.cache/bazel/_bazel_laltenmueller/5f48ff965103b174f3c248651ebad24d/external/sqlite3~/BUILD.bazel:34:8: Compiling sqlite3_test.c failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target @@sqlite3~//:sqlite3_test) 
(...)
external/sqlite3~/sqlite3_test.c:1:10: error: 'sqlite3.h' file not found with <angled> include; use "quotes" instead
    1 | #include <sqlite3.h>
      |          ^~~~~~~~~~~
      |          "sqlite3.h"
(...)
@sqlite3//:sqlite3_test                                         FAILED TO BUILD

Executed 0 out of 1 test: 1 fails to build.
```

After:
```console
❯ bzt @sqlite3//... --test_output=all
(...)
PASSED: @@sqlite3~//:sqlite3_test (see /home/laltenmueller/.cache/bazel/_bazel_laltenmueller/5f48ff965103b174f3c248651ebad24d/execroot/_main/bazel-out/k8-fastbuild/testlogs/external/sqlite3~/sqlite3_test/test.log)
INFO: From Testing @@sqlite3~//:sqlite3_test
==================== Test output for @@sqlite3~//:sqlite3_test:
SQLite3 version: 3.49.0
================================================================================
@sqlite3//:sqlite3_test                                         (cached) PASSED in 0.0s

Executed 0 out of 1 test: 1 test passes.
```