Add postgres 14.18.bcr.3 (#5609)
# Why

Downstream build target fails with:
```cpp
ld.lld: error: undefined symbol: pq_verify_peer_name_matches_certificate
>>> referenced by fe-secure-openssl.c
>>>               bazel-out/haswell-opt/bin/external/postgres+/_objs/pq/fe-secure-openssl.o:(pgtls_open_client)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.048s, Critical Path: 17.01s
INFO: 20 processes: 235 action cache hit, 20 internal.
ERROR: Build did NOT complete successfully
```

It turns out if `fe-secure-openssl.c` gets used, it references
`fe-secure-common.h`, but the `MODULE/BUILD.bazel` file does NOT list
the source (`fe-secure-common.c`), leading to a linking error.

This PR adds this line:
```cpp
LIBPQ_BASE = [
    "src/interfaces/libpq/fe-auth-scram.c",
    "src/interfaces/libpq/fe-auth.c",
    "src/interfaces/libpq/fe-connect.c",
    "src/interfaces/libpq/fe-exec.c",
    "src/interfaces/libpq/fe-lobj.c",
    "src/interfaces/libpq/fe-misc.c",
    "src/interfaces/libpq/fe-print.c",
    "src/interfaces/libpq/fe-protocol3.c",
    "src/interfaces/libpq/fe-secure.c",
+    "src/interfaces/libpq/fe-secure-common.c", <==============
    "src/interfaces/libpq/fe-trace.c",
    "src/interfaces/libpq/legacy-pqsignal.c",
    "src/interfaces/libpq/libpq-events.c",
    "src/interfaces/libpq/pqexpbuffer.c",
]
```

# Validations

Ran:
```
bazel run -- //tools:bcr_validation --check=postgres@14.18.bcr.3
```

Signed-off-by: methylDragon <methylDragon@intrinsic.ai>