Add MODULE.bazel to overlay, it is needed.
I don't know where the recent push to remove MODULE.bazel comes
from, but it breaks the build.

```
$ bazel-7.6.0 build @m4//...
ERROR: ${BAZELDIR}/external/m4~/BUILD.bazel:75:13: ModuleBazelParse external/m4~/m4_package_info/PACKAGE_NAME.results.json [for tool] failed: missing input file '@@m4~//:MODULE.bazel'
ERROR: ${BAZELDIR}/external/m4~/BUILD.bazel:75:13: ModuleBazelParse external/m4~/m4_package_info/PACKAGE_NAME.results.json [for tool] failed: 1 input file(s) do not exist
Use --verbose_failures to see the command lines of failed build steps.
ERROR: ${BAZELDIR}/external/m4~/BUILD.bazel:608:13 CcAutoconfHdr external/m4~/lib/config.h [for tool] failed: 1 input file(s) do not exist
INFO: Elapsed time: 13.337s, Critical Path: 6.51s
INFO: 3770 processes: 2970 internal, 800 linux-sandbox.
ERROR: Build did NOT complete successfully
```