Remove debian10 target due to test failure:
```
generated_message_tctable_gen.h:99:42: error: 'google::protobuf::internal::TailCallTableInfo::FieldEntryInfo::utf8_check_mode' is too small to hold all values of 'enum class google::protobuf::internal::cpp::Utf8CheckMode' [-Werror]
     cpp::Utf8CheckMode utf8_check_mode : 8;
```