Fix libxtrans build failure on Ubuntu 24.04 and bump to 1.5.2.bcr.2 (#6235)
Fixes this build failure on Ubuntu 24.04 by adding a dependency on
`@xorgproto` to provide `X11/Xfuncproto.h`:
```
ERROR: /root/.cache/bazel/_bazel_root/1998f64726edc2c5edfe9e7d7e8d7f19/external/libxtrans~/BUILD.bazel:3:11: Compiling Xtrans.h failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target @@libxtrans~//:xtrans) external/rules_cc~~cc_configure_extension~local_config_cc/cc_wrapper.sh -xc++-header -fsyntax-only -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 20 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/libxtrans~/Xtrans.h:53:10: fatal error: X11/Xfuncproto.h: No such file or directory
   53 | #include <X11/Xfuncproto.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

The build failure was not caught in BCR presubmit for previous versions
because the verification target was set to `//...` instead of
`@libxtrans` or `@libxtrans//...`. This change fixes the presubmit
verification target as well.

---------

Signed-off-by: Shameek Ganguly <shameek@intrinsic.ai>