Fix libpng BUILD symlink, update pcl (#4080)
I'm running into `ERROR: no such package '@@libpng~//':
java.io.IOException: Error downloading
[https://raw.githubusercontent.com/bazelbuild/bazel-central-registry/main/modules/libpng/1.6.47/overlay/BUILD.bazel]
to
/mnt/data/bazel-user-root/4471373f1f0d683ab85e5a49716649a5/external/libpng~/BUILD.bazel:
Checksum was sha256-mUoERhKkrdr8Nud53/UQF7qekzcKHb1u5wGjIPZ43vg= but
wanted sha256-zcPhCWABwguKHRSHV9DCKuoGOv8XHHIUSJ31wenHUV8=` and indeed,
https://raw.githubusercontent.com/bazelbuild/bazel-central-registry/main/modules/libpng/1.6.47/overlay/BUILD.bazel
downloads `../../1.6.44/overlay/BUILD.bazel` instead of the symlink
target.

This PR fixes libpng by just pasting the actual BUILD, and updates pcl
to use that version.