Add envoy_api 0.0.0-20251216-6ef568c.bcr.1
In a routine update from the renovate bot we go an update to envoy_api
(through a chain of dependency). However, this version breaks when
running `bazel mod deps` which fails with the following message:

```
ERROR: module extension @@googleapis+//:extensions.bzl%switched_rules does not generate repository "com_google_googleapis_imports", yet it is imported as "com_google_googleapis_imports" in the usage at https://bcr.bazel.build/modules/envoy_api/0.0.0-20251216-6ef568c/MODULE.bazel:45:31
```

The issue is related to the usage of the extension in googleapis and was
raised in the introduction of this version in [this
comment](https://github.com/bazelbuild/bazel-central-registry/pull/6864#discussion_r2645442266)

This PR introduces an envoy_api module with the fix suggested in that
comment. However if this gets merged I suppose we'll want to propagate
that version upwards?