glfw: 3.4.0.bcr.3; Depends on opengl-registry/egl-registry for header files (#9260)
The existing module does not compile with zero sysroot C++ toolchain
such as `llvm` due to missing OpenGL/EGL related header files:

```
external/glfw+/include/GLFW/glfw3.h:241:12: fatal error: 'GL/gl.h' file not found
  241 |   #include <GL/gl.h>
      |            ^~~~~~~~~
1 error generated.
```

```
In file included from external/glfw+/include/GLFW/glfw3.h:241:
In file included from bazel-out/k8-fastbuild/bin/external/opengl-registry+/_virtual_includes/gl_h/GL/gl.h:2101:
external/opengl-registry+/api/GL/glext.h:37:10: fatal error: 'KHR/khrplatform.h' file not found
   37 | #include <KHR/khrplatform.h>
      |          ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

The changes in this PR are:
- Added OpenGL headers provided by `opengl-registry` BCR module
- Added EGL headers provided by `egl-registry` BCR module
- Removed redundant `overlay/MODULE.bazel`