ci: disable MacOS testing for `rules_zstd`
The `@ape//:zstd` binary current raises `SIGABORT` on MacOS:

```
timefn::clock_gettime(CLOCK_MONOTONIC): Invalid argument
error: Uncaught SIGABRT (SI_0) at 0x1f50001172b on fdd1bd18-d9a1-45ba-889b-bda550b60e49.bazel.cf.macservice.goog pid 71467 tid 259
  bazel-out/darwin_x86_64-opt-exec-ST-d57f47055a04/bin/external/ape~/ape/assimilate/zstd.ape/zstd
  Invalid argument
  Darwin Cosmopolitan 3.3.0 MODE=x86_64; Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 fdd1bd18-d9a1-45ba-889b-bda550b60e49.bazel.cf.macservice.goog 23.5.0
RAX 0000000000000000 RBX 0000000000000006 RDI 0000000000000103
RCX 00007ff7bfeff428 RDX 0000000000000000 RSI 0000000000000006
RBP 00007ff7bfeff440 RSP 00007ff7bfeff428 RIP 000000000055cd79
 R8 0000000000564f43  R9 0000000000000000 R10 000000000055cd79
R11 0000000000000292 R12 00007ff7bfeffe75 R13 0000100080050010
R14 00001000800500a0 R15 0000000000000003
TLS 0000000000582a00
XMM0  00000000000000000000000000000000 XMM8  00000000000000000000000000000000
XMM1  00000000000000000000000000000000 XMM9  00000000000000000000000000000000
XMM2  00000000000000000000000000000000 XMM10 00000000000000000000000000000000
XMM3  000010008005164000001000800501b0 XMM11 00000000000000000000000000000000
XMM4  00000000000000000000000000000000 XMM12 00000000000000000000000000000000
XMM5  00000000000000000000000000000000 XMM13 00000000000000000000000000000000
XMM6  00000000000000000000000000000000 XMM14 00000000000000000000000000000000
XMM7  00000000000000000000000000000000 XMM15 00000000000000000000000000000000
cosmoaddr2line /private/var/tmp/_bazel_buildkite/2b34fd552b54b5a30c5429540ca4fce2/sandbox/darwin-sandbox/6/execroot/_main/bazel-out/darwin_x86_64-opt-exec-ST-d57f47055a04/bin/external/ape~/ape/assimilate/zstd.ape/zstd 55cd79 40a8aa 409dd8 4d4a7b 4d84c1 4d8822 4d9bb9 407072 408463 4045fb
note: won't print addr2line backtrace because probably llvm
7ff7bfefc600 55cd79 systemfive_bsd+21
7ff7bfeff440 40a8aa abort+45
7ff7bfeff460 409dd8 UTIL_clockSpanMicro.cold+0
7ff7bfeff480 4d4a7b FIO_compressFilename_internal+43
7ff7bfeff530 4d84c1 FIO_compressFilename_dstFile+641
7ff7bfeff670 4d8822 FIO_compressFilename_srcFile+386
7ff7bfeff820 4d9bb9 FIO_compressFilename+297
7ff7bfeffa10 407072 main+9906
7ff7bfeffcd0 408463 cosmo+73
7ff7bfeffce0 4045fb _start+133
10008004-10008007 rw-pa- 4x automap 256kB
10008008-1000800b rw-Sa- 4x automap 256kB
1000800c-1000800e rw-pa- 3x automap 192kB w/ 64kB hole
10008010-10008012 rw-pa- 3x automap 192kB w/ 64kB hole
10008014-10008016 rw-pa- 3x automap 192kB w/ 64kB hole
10008018-1000801a rw-pa- 3x automap 192kB w/ 64kB hole
1000801c-1000801e rw-pa- 3x automap 192kB w/ 64kB hole
10008020-10008022 rw-pa- 3x automap 192kB w/ 64kB hole
10008024-10008026 rw-pa- 3x automap 192kB w/ 64kB hole
10008028-1000802a rw-pa- 3x automap 192kB w/ 64kB hole
1000802c-1000802e rw-pa- 3x automap 192kB w/ 64kB hole
10008030-10008032 rw-pa- 3x automap 192kB w/ 64kB hole
10008034-10008037 rw-Sa- 4x automap 256kB
10008038-1000803a rw-pa- 3x automap 192kB w/ 64kB hole
1000803c-1000803e rw-pa- 3x automap 192kB w/ 64kB hole
10008040-10008042 rw-pa- 3x automap 192kB w/ 64kB hole
10008044-10008046 rw-pa- 3x automap 192kB w/ 64kB hole
10008048-1000804a rw-pa- 3x automap 192kB w/ 128kB hole
1000804d-1000804f r--s-- 3x automap 134kB
10008050-10008052 rw-pa- 3x automap 192kB w/ 64kB hole
10008054-10008056 rw-pa- 3x automap 192kB w/ 64kB hole
10008058-1000805a rw-pa- 3x automap 192kB w/ 64kB hole
1000805c-1000805e rw-pa- 3x automap 192kB w/ 64kB hole
10008060-10008062 rw-pa- 3x automap 192kB w/ 64kB hole
10008064-10008068 rw-pa- 5x automap 320kB w/ 96tB hole
6fc00004-6fc00004 rw-paF 1x nsync 64kB w/ 128gB hole
6fe00004-6fe00004 rw-paF 1x g_fds 64kB
```

This will be solved with a `@ape` update in the future.